- name: install mariadb
  yum:
    name:
      - mariadb-server
      - mariadb-devel
    state: latest
- name: Start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
- name: Install packages
  pip:
    name:
      - PyMySQL
      - mysqlclient